<?xml version="1.0" encoding="UTF-8"?>
<TestRun id="9a371bb2-dd4f-4bd2-b454-636e3bd5c36b" name="Fredrik@FKVAIO 2010-09-05 15:39:21" runUser="FKVaio\Fredrik" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <TestSettings name="Local" id="5b82bb5d-938d-47a6-8c5b-afaf40dc0149">
    <Description>These are default test settings for a local test run.</Description>
    <Deployment enabled="false" runDeploymentRoot="Fredrik_FKVAIO 2010-09-05 15_39_21" />
    <Execution>
      <TestTypeSpecific />
      <AgentRule name="Execution Agents">
      </AgentRule>
    </Execution>
  </TestSettings>
  <Times creation="2010-09-05T15:39:21.6294449+02:00" queuing="2010-09-05T15:39:21.9194615+02:00" start="2010-09-05T15:39:22.1604753+02:00" finish="2010-09-05T15:39:22.4584923+02:00" />
  <ResultSummary outcome="Failed">
    <Counters total="1" executed="1" error="0" failed="1" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" passed="0" completed="0" inProgress="0" pending="0" />
  </ResultSummary>
  <TestDefinitions>
    <UnitTest name="Throws_InvalidOperation_when_applying_unregistered_event_on_aggregate_root" storage="c:\source\_projects\nexttask\cqrs.tests\bin\debug\cqrs.tests.dll" id="7b8f9de1-1319-5eba-fa89-c8b24a16ffd2">
      <Execution timeOut="1800000" id="d0515bde-9f21-4b1c-a8ab-e10418380e27" />
      <TestMethod codeBase="C:/Source/_Projects/NextTask/Cqrs.Tests/bin/Debug/Cqrs.Tests.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="Cqrs.Tests.ApplyingEventsToAggregteRoot, Cqrs.Tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="Throws_InvalidOperation_when_applying_unregistered_event_on_aggregate_root" />
    </UnitTest>
  </TestDefinitions>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <TestEntries>
    <TestEntry testId="7b8f9de1-1319-5eba-fa89-c8b24a16ffd2" executionId="d0515bde-9f21-4b1c-a8ab-e10418380e27" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <Results>
    <UnitTestResult executionId="d0515bde-9f21-4b1c-a8ab-e10418380e27" testId="7b8f9de1-1319-5eba-fa89-c8b24a16ffd2" testName="Throws_InvalidOperation_when_applying_unregistered_event_on_aggregate_root" computerName="FKVAIO" duration="00:00:00.0619098" startTime="2010-09-05T15:39:22.2294792+02:00" endTime="2010-09-05T15:39:22.3734875+02:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="d0515bde-9f21-4b1c-a8ab-e10418380e27">
      <Output>
        <ErrorInfo>
          <Message>Test method Cqrs.Tests.ApplyingEventsToAggregteRoot.Throws_InvalidOperation_when_applying_unregistered_event_on_aggregate_root threw exception System.ArgumentNullException, but exception System.InvalidOperationException was expected. Exception message: System.ArgumentNullException: Value cannot be null.
Parameter name: source</Message>
          <StackTrace>    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Cqrs.EventRegistry.GetHandlerForEvent(IDomainEvent event) in C:\Source\_Projects\NextTask\Cqrs\AggregateRoot.cs:line 28
   at Cqrs.AggregateRoot.Apply(IDomainEvent event) in C:\Source\_Projects\NextTask\Cqrs\AggregateRoot.cs:line 71
   at Cqrs.Tests.ApplyingEventsToAggregteRoot.Throws_InvalidOperation_when_applying_unregistered_event_on_aggregate_root() in C:\Source\_Projects\NextTask\Cqrs.Tests\Applying_events_to_aggregte_roots.cs:line 28
</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
</TestRun>